### ISSUE TITLE
<Scripts /> throws warning of props object containing a "key" prop being spread into JSX.

### ISSUE THREAD

**Issue by lithdew** [TanStack/router#1138]
### Describe the bug

I upgraded to v1.15.12 using Vinxi w/ React SSR streaming and got errors about improperly spread props in <Scripts/>. The errors started to appear since this commit: https://github.com/TanStack/router/commit/3aac5c6971f5fb775fd6b57b49ff7dac21766e81

Important to note though that I understand these changes are experimental, and I assume that how a Vinxi + Tanstack Router setup should be done is being simplified/refactored for Tanstack Start at the moment.

I made my best guess in figuring out how to plug in the new utility functions in the commit above and pasted a screenshot of my setup below.

### Your Example Website or App

See screenshots below.

### Steps to Reproduce the Bug or Issue

<img width="647" alt="image" src="https://github.com/TanStack/router/assets/63115601/216b0a51-8004-4f8f-af4e-8bf514af6300">
<img width="1487" alt="image" src="https://github.com/TanStack/router/assets/63115601/7f8219c3-c05a-422a-826f-86bfe8306687">

### Expected behavior

For the warnings to not appear.

### Platform

- OS: macOS
- Browser: Chrome
- Version: v1.15.12

**Comment by SeanCassiere** [comment]
This should be fixed given that we are now [setting a key on all the scripts](https://github.com/TanStack/router/blob/527e52d96ab826a02dca06647311badb6f50bffb/packages/react-router-server/src/client/Scripts.tsx#L42-L44) being rendered.

**Comment by advancedtw** [comment]
Still experiencing the same issue event tough I'm on 1.26.1.  
The problem is not about the Asset component missing a key but the attrs object containing a key 
```jsx
// Asset.tsx attrs may contain a key
return <style {...attrs} dangerouslySetInnerHTML={{ __html: children }} />
```
