### ISSUE TITLE
Throw redirect in beforeLoad doesn't work on bun production bundle

### ISSUE THREAD

**Issue by adrifer** [TanStack/router#2819]
### Which project does this relate to?

Start

### Describe the bug

When using bun, on a production build redirect doesn't work at least on beforeLoad (it correctly works using vinxi dev).

### Your Example Website or App

https://github.com/TanStack/router/tree/main/examples/react/start-basic

### Steps to Reproduce the Bug or Issue

1. Using the starts-basic example. Add preset: "bun" on app.config.ts
2. Run bun run build
3. Run bun run .output/server/index.mjs
4. Navigate to /redirect
5. White screen will show. No errors showing

### Expected behavior

It should navigate to /posts

### Platform

- OS: Windows and MacOS
- Browser: Edge
- Version: 131.0.2903.51

**Comment by adrifer** [comment]
Sorry I cannot provide a full repro in StackBlitz but as far as I know, they don't support bun

**Comment by schiller-manuel** [comment]
does this only occur with bun?

**Comment by adrifer** [comment]
Yes, only on bun on production. Basically I tested these scenarios:
- Bun (dev mode): works
- Bun (prod mode): fails
- Node (dev mode): works
- Node (prod mode): works

**Comment by schiller-manuel** [comment]
does the build output differ depending on bun vs node?

**Comment by adrifer** [comment]
Now that I've seen on Bun output we have a Bun.serve at the end, I'm throwing some console.logs to see if I can find more info :)

**Comment by adrifer** [comment]
No luck so far, it seems I cannot repro the same using standalone vinxi...

**Comment by adrifer** [comment]
After debugging a little bit more and modifying the .output/server/index.mjs file to understand what is making Bun not doing the redirect, I found changing this line:
```diff
const server = Bun.serve({
  port: process.env.NITRO_PORT || process.env.PORT || 3e3,
  websocket: void 0,
  async fetch(req, server2) {
    const url = new URL(req.url);
    let body;
    console.log(url.pathname);
    if (req.body) {
      body = await req.arrayBuffer();
    }
    const response = await nitroApp.localFetch(url.pathname + url.search, {
      host: url.hostname,
      protocol: url.protocol,
      headers: req.headers,
      method: req.method,
      redirect: req.redirect,
      body
    });

    if(response.status === 307) {
+     return new globalThis.Response(response.body, {
-      return new globalThis.Response(null, {
        ok: response.ok,
        url: response.url,
        status: response.status,
        statusText: response.statusText,
        headers: response.headers,
        redirected: response.redirected,
        bodyUsed: response.bodyUsed
      });
    }
    return response;
  }
```

So basically it seems something in the response body is what is making bun to not do the redirect...

**Comment by adrifer** [comment]
Ok, seems I've found the issue.

When we do a redirect with Bun, but the body is an empty ReadableStream, bun returns and empty response with no headers or body.

I've created an issue on Bun repo: https://github.com/oven-sh/bun/issues/15320

**Comment by ebramanti** [comment]
@adrifer This is resolved now that Bun v1.2.9 is out?

**Comment by adrifer** [comment]
I think so but I didn't have time to test it yet. Probably later today I will be able to verify it :)

**Comment by kasulio** [comment]
I had the same problem aswell and just tested it again with bun 1.2.2 where it still occurred. After updating to 1.2.9 it worked without issues so I also believe this can be closed 🥳

**Comment by adrifer** [comment]
I had the same result so I'm closing this! Thanks!!
