### ISSUE TITLE
Nested layouts do not render

### ISSUE THREAD

**Issue by rubanooo** [TanStack/router#363]
### Describe the bug

When nesting two layouts directly, the first layout never renders.

### Your Example Website or App

https://codesandbox.io/p/sandbox/fervent-hill-t4him1

### Steps to Reproduce the Bug or Issue

See example app for instructions

### Expected behavior

Both layouts render.

### Platform

- any

**Comment by tannerlinsley** [comment]
Pretty sure this is fixed in the latest version. Both routes are now rendering in your example

**Comment by Moshyfawn** [comment]
Hm, I can't seem to get it working in `"@tanstack/react-router": "^0.0.1-beta.25"`
Here's [a repro csb](https://codesandbox.io/p/sandbox/confident-goldberg-xvsjzq?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A25%2C%22endLineNumber%22%3A45%2C%22startColumn%22%3A25%2C%22startLineNumber%22%3A45%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl9zkf3e9000alqiphi669wk8%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fsrc%252FApp.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clapzbbut01hu2e67yvz361ol%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fprivate%252Fmanagement%252F1%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clapzb1mb01cz2e67ewbeflno%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by greatcrypter** [comment]
is this already fixe

> Pretty sure this is fixed in the latest version. Both routes are now rendering in your example

this issue still existed in version 0.0.1-beta.83
