### ISSUE TITLE
Docs: StackBlitz examples fail to load due to incorrect embedding

### ISSUE THREAD

**Issue by aaronmcadam** [TanStack/router#400]
### Describe the bug

When the example loads, we see the following:
> Unable to run Embedded Project
> Looks like this project is being embedded without proper isolation headers.

Here's a screenshot:
<img width="1049" alt="CleanShot 2022-11-25 at 17 34 36@2x" src="https://user-images.githubusercontent.com/37928/204034004-c10b1473-5e3e-4216-a406-7d8d91b6c333.png">

### Your Example Website or App

https://tanstack.com/router/v1/docs/examples/react/kitchen-sink?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://tanstack.com/router/v1/docs/examples/react/kitchen-sink?file=src%2Fmain.tsx
2. Wait for StackBlitz to load
3. See the error

### Expected behavior

As a learner, I expected to play with the example and see how it works.

### Screenshots or Videos

<img width="1049" alt="CleanShot 2022-11-25 at 17 34 36@2x" src="https://user-images.githubusercontent.com/37928/204034004-c10b1473-5e3e-4216-a406-7d8d91b6c333.png">

### Platform

- OS: macOS
- Browser:  Firefox
- Version: 108.0b6

**Comment by oqx** [comment]
It looks like it was taken down completely recently:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/13574166/205464583-70912f56-15bd-4454-8b58-4734bed5d640.png">

**Comment by tannerlinsley** [comment]
This should be fixed now.

**Comment by aaronmcadam** [comment]
Hey @tannerlinsley I'm still seeing issues on the example pages, such as  https://tanstack.com/router/v1/docs/examples/react/basic?file=src%2Fmain.tsx

**Comment by kubijo** [comment]
As do I on `Firefox@125.0.2`
