### ISSUE TITLE
Route component is rendered without route context from async beforeLoad with pendingComponent

### ISSUE THREAD

**Issue by longzheng** [TanStack/router#4998]
### Which project does this relate to?

Router

### Describe the bug

When using a route with a pending component, the route's component is rendered without awaiting async `beforeLoad` leading to incomplete context data, leading to `undefined` errors.

For example with this route definition with a `beforeLoad` that has an awaited promise, a `pendingComponent` and a `component`

```tsx
export const Route = createFileRoute('/posts')({
  beforeLoad: async () => {
    console.log('beforeLoad');

    const test = await new Promise<string>((resolve) =>
      setTimeout(() => resolve('hello world'), 1000)
    );

    console.log('beforeLoad done');

    return {
      test,
    };
  },
  component: PostsLayoutComponent,
  pendingComponent: () => 'loading',
});
```

In the route component, when I try to use the context

```tsx
function PostsLayoutComponent() {
  console.log('route component render');
  const { test } = Route.useRouteContext();
  console.log('Route context test:', test);
```

the type of `test` is inferred as `string`, but it's rendered with `undefined` while the component is pending.

I'm not sure if the bug is either
- the route's `component` should not be rendered during pending state
- the `beforeLoad` should be awaited when there is a pending component

The **pending component is a significant factor** because if I remove the pending component, then this bug does not occur. The route component is always rendered with the correct context from awaited `beforeLoad`.

Note: the repro has `defaultPendingMs: 0` set to always show the pending component.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-onocc5sg?file=src%2Froutes%2Fposts.route.tsx

### Steps to Reproduce the Bug or Issue

1. Open browser devtools console
2. In the preview, click on "Posts"
3. See console logs for route component rendering with missing context value for the property `test`

```
beforeLoad
route component render
Route context test: undefined
beforeLoad done
route component render
Route context test: hello world
````

### Expected behavior

I expect the route component to be rendered with the route context with `beforeLoad` awaited, as the types suggest.

### Platform

- Router / Start Version: 1.131.27
- OS: Windows
- Browser: Chrome
- Browser Version: 139.0.7258.67
- Bundler: vite
- Bundler Version: 6.3.6

**Comment by longzheng** [comment]
@Sheraff I noticed you started working on a draft pr.

Do you know what is the reason behind the route component rendering while pending if there is a pending component?

**Comment by Sheraff** [comment]
> Do you know what is the reason behind the route component rendering while pending if there is a pending component?

I do not, I wanted to see if this was due to one of my recent PRs, but it looks like it's been the case for a while. It is definitely a bug though.

Did this use to work for you and the behavior changed? And if so, do you know at which version it broke (or at least, which version you had before)?

**Comment by longzheng** [comment]
> Did this use to work for you and the behavior changed? And if so, do you know at which version it broke (or at least, which version you had before)?

I'm not sure either. I stumbled across this while trying to refactor some tanstack query in my beforeLoad.

I had assumed my `ensureQueryData` code were always awaiting the query but turns out it was just getting the cache data (synchronously).

So I also don't know if the beforeLoad behaviour changed or if it has always been like this.

EDIT: for what it's worth my project was using router 1.129.8

**Comment by longzheng** [comment]
I also don't know if the route component was always rendered while pending.

**Comment by longzheng** [comment]
@Sheraff After a lot of trial an error, I narrowed down the release that changed the behaviour, v1.92.13 and specifically this change https://github.com/TanStack/router/pull/3095 by @schiller-manuel

### Repro
[Repro with v1.92.13](https://stackblitz.com/edit/tanstack-router-rsbrwytc?file=src%2Froutes%2Fposts.route.tsx,package.json&preset=node)
[Repro with prior release v1.92.11](https://stackblitz.com/edit/tanstack-router-rd91mkqa?file=src%2Froutes%2Fposts.route.tsx,package.json&preset=node)

### Repro steps
1. Open devtools console
2. Click on "Posts" tab
3. See `Route context test` has correct value (`hello world`)
4. Click on "Home" tab and then click on "Posts" tab again
5. See `Route context test` has `undefined`

So in version 1.92.11, the sequence is as follows
```ts
// first posts tab load
beforeLoad
pending component render
beforeLoad done
route component render
Route context test: hello world // correct value

// second posts tab load
beforeLoad
route component render
Route context test: hello world // correct value
beforeLoad done
```

In version 1.92.13, the sequence is
```ts
// first posts tab load
beforeLoad
pending component render
beforeLoad done
route component render
Route context test: hello world // correct value

// second posts tab load
beforeLoad
route component render
Route context test: undefined // incorrect value
beforeLoad done
route component render
Route context test: hello world // correct value
```

Looking at #3095 more closely and the issue #3051 it was trying to fix, I wonder if it would make more sense for the [change](https://github.com/TanStack/router/commit/d16fb426f6e3108bdd341602064d71f00ca393d5#diff-2ac234f610fa0e0c2146252c10a5266af9c5b6d0b63659a0fa4c9f2c4472596aL2400) to be
```diff
                    context: {
+                     ...prev.__beforeLoadContext,
                      ...getParentMatchContext(),
                      ...prev.__routeContext,
-                     ...prev.__beforeLoadContext,
                    },
```
so that the previous beforeLoad context is still merged (rather than omitting entirely) but can be overwritten by the route context (is my interpretation of the code, I could be wrong).

Having said that, I'm still a bit confused why the route component is rendered (but not shown) if there is a pending component but from what I can see that behaviour has always been there so not sure if that's a bit of a red herring.

**Comment by longzheng** [comment]
@Sheraff I made a fix for this using my proposed change above. https://github.com/TanStack/router/pull/5002 

I used your test in your draft PR as a base but tweaked it a bit to wait for the beforeLoad to be resolved completely before checking `expect(resolved).toBe(2)`

**Comment by phibr0** [comment]
I think this might be related to my issue #4614

**Comment by paul-sachs** [comment]
Just ran into this. In my case, the context determines the layout being rendered so it's very hard to work around. Has anyone come up with ideas?

**Comment by Tekpakma** [comment]
Facing this too. For a month ive been now manually Suspending my Component(s) if the required Context is undefined, which luckily works quite nicely, but is also inconvenient.

**Comment by schiller-manuel** [comment]
fixed in https://github.com/TanStack/router/releases/tag/v1.140.1

**Comment by demitrin** [comment]
@schiller-manuel I'm still seeing evidence of this after updating to version v1.140.1. What i'm seeing is that downstream the `resource` can be undefined, causing an uncaught error in components (that isn't caught by typescript)

My tanstack query config is:

```
export const router = createRouter({
  routeTree
  defaultPreloadStaleTime: 0,
  defaultPendingComponent: DefaultPendingComponent,
  defaultPendingMinMs: 200,
  context: {
    queryClient,
  },
})
```

and a route like

```
export const Route = createFileRoute(
  'my-route'
)({
  validateSearch: zodSchema,
  beforeLoad: async ({ params, context }) => {
    const { resourceId } = params

      const resource = await context.queryClient.fetchQuery({
        ...getResourceById({
          path: { resourceId },
        }),
      })

      if (!resource) {
        throw new NotFoundError()
      }

      return { resource }
    
  },
  errorComponent: ResourceErrorComponent,,
  component: ResourceDetailPage,
})
function ResourceDetailPage() {
  const { resource } = Route.useRouteContext()
  resource.myProperty // throws for undefined
}
```

**Comment by Sheraff** [comment]
> I'm still seeing evidence of this after updating to version v1.140.1. What i'm seeing is that downstream the `resource` can be undefined, causing an uncaught error in components (that isn't caught by typescript)

Under which conditions does this reproduce the error? (Like maybe "navigating many times in quick succession" or something like that)

**Comment by demitrin** [comment]
I'm seeing it on back navigation from a route that also has context. Roughly something like:

current page: Root route (context loaded async) -> Parent route (context loaded async) -> child route 1 (context loaded async)
navigate back to page: Root route (context loaded async) -> Parent route (context loaded async) -> child route 2 (context loaded async)

i'm getting undefined in child route 2 page (ResourceDetailPage above)

Worth mentioning I'm seeing this relatively consistently. Both child route 1 and 2 have search schema, pending components, and beforeLoad + context

**Comment by demitrin** [comment]
I have another example that seems to exhibit the same behavior, but only for 1 of our routes.

Fresh load of a page with this kind of flow page heirarchy

current page: Root route (context loaded async) -> Parent route (context loaded async) -> child route (beforeLoad uses parent route context)

in child route, we're seeing undefined context from root route in the child route's `beforeLoad`. This is only on fresh load. when navigating to the page from another, it works. likely because the parent route (which uses tanstack query) has the payload cached. for all of these we're using `fetchQuery` in the beforeLoad section

I really appreciate the time you're taking to look at this. Let me know how else i could be helpful

UPDATE

The undefined context from root route to child route seems to be reliably undefined on fresh reload using `fetchQuery` since version 1.40.1. Downgrading to version 1.40.0 seems to allow the context to propagate. I've turned off pending components for now and downgraded to 1.40.0

**Comment by schiller-manuel** [comment]
@demitrin  can you please create a new github issue including a reproducer?

**Comment by demitrin** [comment]
@schiller-manuel let me know if this is good: https://github.com/TanStack/router/issues/6068
