### ISSUE TITLE
index on nested layout in windows

### ISSUE THREAD

**Issue by aliakbarazizi** [TanStack/router#936]
### Describe the bug

Its not possible to create index on nested file structure for layout.

Imagine I have _panel.tsx for my panel layout, and I want to have index for panel dashboard.

I can do it by creating file named _panel.index.tsx, but if I wanted directory structure its impossible.

If I create a _panel/index.tsx, the route generator doesn't understand the different between `_panel.tsx` and `_panel/index.tsx`

here is the result in `routeTree.gen.ts`
```
import { Route as PanelRoute } from "./pages/_panel";
import { Route as PanelIndexRoute } from "./pages/_panel";
```

I can see this is node issue because of `index` name, but it should be some work around to keep directory structure and have this.

This issue only exist in windows.

### Your Example Website or App

https://stackblitz.com/edit/github-mbphlw

### Steps to Reproduce the Bug or Issue

The issue only exist on windows
1. clone this on windows https://stackblitz.com/edit/github-mbphlw
2. run `yarn tsr generate`

### Expected behavior

routeTree.gen.ts should be like this

```
import { Route as PanelRoute } from "./pages/_panel"
import { Route as PanelIndexRoute } from "./pages/_panel/index"
```
instead of

```
import { Route as PanelRoute } from './pages/_panel';
import { Route as PanelIndexRoute } from './pages/_panel';
```

### Platform

- OS: Windows
- Browser: -
- Version: 1.1.6

**Comment by aliakbarazizi** [comment]
I guess the issue is because of this line

https://github.com/TanStack/router/blob/main/packages/router-cli/src/generator.ts#L371C22-L371C22

from this commit

https://github.com/TanStack/router/commit/0b2cd04ab736e33a05c5608f5c9caaf789479f3e

**Comment by adamhemzal** [comment]
I can confirm - I have the same issue. 

![image](https://github.com/TanStack/router/assets/22219315/dfbb453d-aeec-4a34-ac52-3bb298840269)


And I'm getting this error:

![image](https://github.com/TanStack/router/assets/22219315/fbe509cb-19c2-4da8-ab22-5c07c43c9a03)


![image](https://github.com/TanStack/router/assets/22219315/c2b8961e-b95d-48a2-b110-53acfff85a9f)

**Comment by tannerlinsley** [comment]
I believe this is now fixed in the latest version of the router CLI and vite plugin

**Comment by SaiKai** [comment]
not fixed yet, but i created a pull request with the needed fix #973
